#!perl
use strict;
use warnings FATAL => 'all';

my $mutationRatio = 0;
for( my $i=0; $i<24000000; $i=$i+1 ){
	$mutationRatio = $mutationRatio + 0.000000033*(1-$mutationRatio) - 0.000000033*$mutationRatio*0.33333;
}
print "$mutationRatio\n";


$mutationRatio = 0;
for( my $i=0; $i<2200; $i=$i+1 ){
	$mutationRatio = $mutationRatio + 0.0005*(1-$mutationRatio) - 0.0005*$mutationRatio*0.33333;
}
print "$mutationRatio\n";



my %DNA =  ( 0 => 'A', 1 => 'C',  2 => 'G', 3 => 'T');


my $seq1="";
for( my $i=0; $i<2000; $i=$i+1 ){
	my $random_number = int(rand(4));
	$seq1 = $seq1 . $DNA{$random_number};
}

my $simulationTimes = 0;
my $seq2 = $seq1;
while( 1 ){
	$simulationTimes = $simulationTimes + 1;
	my $random_position = int(rand(2000));
	my $random_number = int(rand(4));
	substr($seq2, $random_position, 1) = $DNA{$random_number};
	my $numberDiversity = 0;
	for( my $i=0; $i<2000; $i++ ){
		if( substr($seq1, $i, 1) ne substr($seq2, $i, 1) ){
			$numberDiversity = $numberDiversity + 1;
		}
	}
	if( $numberDiversity >= 978 ){
		last;
	}
}
print "$simulationTimes\n";
print "$seq1\n";
print "$seq2\n";


my $a1="CCTATGGCACAGCGGTTGGCGCTTGCGCGGTCACCGGCGACTGGTCGATTGGCTTGTTAAATGCGTATGGGACATATCTTAAGCAAAGTCATGAGTGTGCA--TGAGA--------TAGTCGCAGTTCTTTGACACAGTATTAATTTCAATCCTAACTAAGACCAATAACATCCAGAAGGTCGTACTCAACAGCGGGTAC----GTTTGACGTGTGATCTAGTTTGGCTCCCGCCAGCATATAGATGGTAAAGCATGTCTAAGATCAGGCTCTTCCCTATGCCTGGCATATGGTCATCGCGTGATTGAGTCTC-CAGGGTTCAATAAC-GACGCCTTTGATGTTTTATTGTACCGACTGAGGTTTTCACGACTGTAGAGAGTATAGGAACTATCTAGCCTC------GCTG-CTTAAACATTCGAGCGGATTGAAATATTGCGGATTCTTCCATTGGATTCAA--AGCATCTCCCGAGCTTCATTCGTGTGTGGCAACAAGCGAAAGTCCGACC------GTAAGTGAATGCCCTTGACGGACTTCGGTGTTAAGGGCTATGGACTTCTCGGTTTCGT----ATG-GATCTGCGGAATTGCTGTAGATACATAGGGAGAGTGGGCAACGATCTCCCGCGGTAGAGTGGTATGTGTGACCGGTGAAGTTTTAGTCATCTA-TTATTCCTCCCGGCATCGAAGCGCTCAGCCACTGCT--TATCACATGATCTGTCCCAGCGTTGGCGCCTTATCGGAAAATTACTCTCCGCGCCATGTCTTCAGTAGATACATAACGATTTGTATGACGGTTGGAC-----CGTAACGTAATTGAGAGGGTTAGCGGCAT-GCTGTTGCGGATCTCAGTGAAGGGCTGTCTATATCTTGAACCCT-AGAATACTGGTTACAGGAGCTCCGCGTTCCACCGAGTAATCCTAATTCGTCCCAGAGATATGTTCGAAA----ACTAGTCCGGCATGCCCGTGTATCTCAAC-----AATGGATATGTCCTTGCATCGGTGGGCGCCGGTATTGGAGCAGTTATCCCGGCTACAATGGAGATTTAGAACTATATG--CCTTTACAAGGCTAACCTCGACTTTAGTGTGCCCATCTCGAACAGTTTGCGGTGAATGGCTCTCACAGTTTCACTGGCCAAGTTGCCTAATAACGCAGCCCCTAGTTACAAAGAGACCACAATT-------GACCTGCATCAGTTCACATACCAGATTCGATTTTGTACCACCCGCGTTGGTGGAGTCGCCGAACGC--CCGGAAACGGCTCCGCGCAGC-AGCTTTTTCGGTAGCTCTGATAGACAGGCATGACGTTAGTTAGTTGAATTAAACCAAGGAGGAACGGCGTTGCGGGCCACGCCTTCAGACAGAAGGCTTGAATTTTGGACGCA----TTCAATCTAAT--ATGAGCTCACTGTCACATCGACGAAGAGCTGGACAGCGTACTTGCCGATTTGGGAACAGATTACCGTACCGATGAAGGAAAGATC-TGTGACC-TATATTTCCGAATCTTTCCGCTATTTCTAAGTAAAAACCGTGAAGACAATGTTCCCGGGCCACTGG---TACTGATCCCCGGGCCCAGCACGGAGGTCAGCTCAAGGGTCCGTTCTTGGTTTGCTACAGTCGCTTTTTTATCGCACCTCGCCCATGGACACTTGTGAATGTACTCTATTCCGTCTGAGTTTCGTCTAATGCTCCTACCCATTACGTGCTATGACGGCGGCAGCTAATAAGGTTCATGAATATCGGTCAAAGAGGACTGCTTAATAACAGGAGACTTTAACCCTAGAGTGTCAGATAAAAGACTCTCGAAGCTGCGTAACAATCTGTGACCCGGCACGGTTAGTCAAC-AC-CCTTGTCAACATAAGCGG--CAGCACACGCGAAGTTAGGAAGCAGACCGCTGATTCGTATGCTAGTCTTCCAAGACGTAGGTTTCACCTTCAT--GGGACCCGGACCCGGGTTAGATTACTAAATCGGGTATCAGTAGCTGTAAGTGAATTAG---GAGTACTCTGACCTATACGCAGAGCGTGAGTCCCCACTGCCCG";
my $a2="AGTATCCCGACGCGGTTACTGCTTAAGCGGCTAACGTCCGCCGTTCCATGGGCTTCCTAGATTCCAAGGG-----ATCTT--GCGCTCTCATGAG---GCATTTGAGAGGGCGTGGTGGTTCCAATTCTTGGTAATAGCGTGCCTTAGAATCCTGGCTCAGAACGAAGCGATCGATGTGGTAGTGCTGGCTTGATGGCACAGGAGATTCGCGT-TCAT-TA--TATGCGCCCGGTCCCAGAGATATGGAAAATCGCACAGGAGATAGGACTCATCTACTTGGGTAGCGTCAGGGAATTTCTAGATAGAGTCACTCAGGAT--AGTTACAGACGGCTGCGATGGTATAGTTCACTGAAATATCTTCCGCCGAC--TCCAGCCTAT-GCGTCAACCCAACCGCCAGTGGGCAGACTCACAC---CG-GTAGATTGACATGGTGCGGATTCTACTATTGG--GCAATGAGGATCTCCGGCTCTTCTTTCGTGTCTGTTACACGGCGAAAGACCGAACATTCTGGTACGAGAACGC------CGGACTACTACATTAACGGC---GGGCTAGT--TTTTCGTCTTAATGAGAGCTGCGGGACCGCGGCTCATACCTAGCCAACTTCTTGCACTATCAAACTGCGTAGATTGGCAGGAGTGTACAAAGCTGATATAGGCA-CTATTTAGGGTTCGCGAAATTTGACCGCTCTACGTCAGCTGATAGCA-ATGTGCT-TGCCAGTGATGGGCCCTAAGGGTGCAATTACGCTACGGGCCAGTACTCTAGTAATTACAGAGTGATCAGTTCGTCGTGTGTACACCGACGAAAGGGAATTAATAG-----ACTGCATGGGTGTACAGCCACACGGT-ACCTACCGATGATAACTGCAACCGTCAGCGT-GTGGTGTCCGCTACGGCGACCGCCAGCTAATAATCGTACTCCTTC----AGGTAGGTACCTAATTCGACTAGTTGGGAATTCACGCTTTGGGCACCCACGGACTTGATAGTACTTTGC--TGTTGGGCGGCG---ACGTCGCAGTCGTGCGGGGTGCTATTAAACGGTTCCCCTTAATGGTCCGT--CTCGGTAAATCTAAGTTTTGGGGGGACCATGCCTATGACTTTGCACTCAACCCCTTTGCCAGGTGTGGATGCGATGTTGGTTCATTTGACAGCTCCT-------AAGATCACACCATTCGAGAGGGACCAGTGTTCGTTAGAATTACACTGTCCATCTTGTACCATCCGCGAGTATGCAGGAGTAGAAAGCTTCCGG--TCTGCTGTACG-AGCGCGCGTTGTACGTAGACTTGTCAGGTCCCCTTGACGCTAGTCAAAGGAGTTAAAATAAGTTGGAACGCTCTTCCCGTGCAAGCTCCCCCACTGTCGGCTCGGTTTTTGGATAGAGTTGTTCGATCTACTGCCTAATC-CACCATGA-AT--ATTCATAGTT--ACATACTAATCGCCGTGTGGGGGCGACCTTCAAGTATCGAT--TTCCAAGGTCGTACTACCAGTTAATTTCGGAGCTCTTCGGTATTGCTCAGGGGTCTCCGTGTGGACATAGAGCGCTG---ATTGGTCATTGTGGTCCGGGGTGGGATCGCGTAGGCGAGCTTGAACAACCGTTCCACTCTCACTACTGAAGTCTTTTAATCGCAAGAAGCCTCTCGACACCCGAGAATAAACTAGTTTCCGTTGTAATAGCCTCAAAACGGAACAGACTTTACGTGCCCGGAGACCGCCACCCAACTACCTGCCCGAATGAAGGTACGTGTTCACCGCTTAATAACGCATGCATGTAAAGACAGCGTGCCCGATGTCGATCTCTCGTATGTGTCCAGCAGTCCGTGCGTCCGAACTTGTAGGCGACTACGCAATATCTTTAGTAGCTGACGAGCGTACG----GTGAGGCAGCAGTTCGCGTCAGCGTTTGCTTGCCGACCTTAACGCACGTCTCAATATCATACGGCGCCGGGAGC--ACATACATCAGGAAGTGGGGTAACCATA-CCGTTACTG--GTCGGGTGAATAATCAGAGTTATCCACAGCACGGGATTCCCCGCTCGAGG";


my $a1p=0;
my $a2p=0;
my $correct = 0;
for( my $i=0; $i<length($a1); $i=$i+1 ){
#	print "substr($a1, $i, 1)\tsubstr($a2, $i, 1)\t$a1p\t$a2p\n";
	if( (substr($a1, $i, 1) ne "-") && (substr($a2, $i, 1) ne "-") && ($a1p==$a2p) ){
		$correct = $correct + 1;
	}
	if( substr($a1, $i, 1) ne "-"){
		$a1p = $a1p + 1;
	}
	if( substr($a2, $i, 1) ne "-"){
		$a2p = $a2p + 1;
	}
}

print "$correct\n";
